# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

# On everypush in the main branch this setup will start doing its job 
on:
  push:
    branches:
     - main

# It will run the job of deploy on ubuntu-latest
# and perform the following actions with their names and uses 
# Its very similar to how we write code in adocker file. 
# You will be creating an api token from yout pypi login. This is the most standard way of doing things 
# Copy that token and paste the token in the secrets of your github repository. 
# You can access that token here then. 
# After commiting all the changes, go to actions and deploy the changes 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
